"""Updated norms field from varchar to string

Revision ID: 003c73624643
Revises: 9329e37ffc0f
Create Date: 2024-01-11 16:48:29.703625

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "003c73624643"
down_revision: Union[str, None] = "9329e37ffc0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "permissions",
        "perm",
        type_=sa.String(),
        existing_type=sa.VARCHAR(length=11),
        nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "permissions", "perm", existing_type=sa.VARCHAR(length=11), nullable=False
    )
    # ### end Alembic commands ###
