"""Added permissions for patches

Revision ID: 09f40a124cec
Revises: e6d69dbd31f4
Create Date: 2024-01-11 14:19:27.596015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09f40a124cec"
down_revision: Union[str, None] = "e6d69dbd31f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("membership_id", sa.Integer(), nullable=False),
        sa.Column(
            "perm",
            sa.Enum("owner", "moderator", "trustee", "facilitator", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"], ["memberships.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permissions")
    # ### end Alembic commands ###
