"""Added unique constraint of (persona_id, community_id)

Revision ID: 0cc888c39995
Revises: 003c73624643
Create Date: 2024-01-12 12:36:44.188003

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0cc888c39995"
down_revision: Union[str, None] = "003c73624643"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "membership_index", "memberships", ["persona_id", "community_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("membership_index", table_name="memberships")
    # ### end Alembic commands ###
