"""Add images

Revision ID: 13e1f5effca2
Revises: fddc819c8923
Create Date: 2023-10-17 12:52:50.030650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13e1f5effca2"
down_revision: Union[str, None] = "fddc819c8923"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("personas", sa.Column("image_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "personas", "images", ["image_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "personas", type_="foreignkey")
    op.drop_column("personas", "image_id")
    op.drop_table("images")
    # ### end Alembic commands ###
