"""Added mod_metadata field

Revision ID: 151a1e05b9a5
Revises: d58569e80615
Create Date: 2024-08-23 18:47:06.226526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151a1e05b9a5'
down_revision: Union[str, None] = 'd58569e80615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('mod_metadata', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'mod_metadata')
    # ### end Alembic commands ###
