"""Update nullable audio

Revision ID: 18e202334448
Revises: d90ed1a9d104
Create Date: 2023-12-07 23:10:48.751869

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18e202334448"
down_revision: Union[str, None] = "d90ed1a9d104"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("posts", "audio_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("posts", "audio_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
