"""Added posts table

Revision ID: 1b09b63e94fb
Revises: 27fab7212f6f
Create Date: 2023-10-03 13:54:12.094667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b09b63e94fb"
down_revision: Union[str, None] = "27fab7212f6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("audio_link", sa.String(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("foraConv_id", sa.Integer(), nullable=True),
        sa.Column("in_reply_to", sa.Integer(), nullable=True),
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("activation_time", sa.DateTime(), nullable=True),
        sa.Column("expiration_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    # ### end Alembic commands ###
