"""Added ai_mod_output field to Posts

Revision ID: 25ac367fac25
Revises: 44eae1bd6774
Create Date: 2024-02-25 10:22:35.614569

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25ac367fac25"
down_revision: Union[str, None] = "44eae1bd6774"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mod_reviews", "reviewer_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column("posts", sa.Column("ai_mod_output", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "ai_mod_output")
    op.alter_column(
        "mod_reviews", "reviewer_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
