"""Added community-level flags to db

Revision ID: 3918b51efc35
Revises: a114e2db5131
Create Date: 2024-02-23 00:10:31.201129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3918b51efc35"
down_revision: Union[str, None] = "a114e2db5131"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community_flags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "community_flags_index",
        "community_flags",
        ["community_id", "label"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("community_flags_index", table_name="community_flags")
    op.drop_table("community_flags")
    # ### end Alembic commands ###
