"""Added creator_id and metadata to communities

Revision ID: 399cfe3cc45b
Revises: cae904fb793d
Create Date: 2024-01-30 23:42:57.692957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "399cfe3cc45b"
down_revision: Union[str, None] = "cae904fb793d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("communities", sa.Column("metadata", sa.String(), nullable=True))
    op.add_column("communities", sa.Column("creator_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "communities", "personas", ["creator_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "communities", type_="foreignkey")
    op.drop_column("communities", "creator_id")
    op.drop_column("communities", "metadata")
    # ### end Alembic commands ###
