"""Added reviewer_id to mod_reviews

Revision ID: 44eae1bd6774
Revises: b0d1252922e8
Create Date: 2024-02-24 10:49:20.980813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44eae1bd6774"
down_revision: Union[str, None] = "b0d1252922e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mod_reviews", sa.Column("reviewer_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "mod_reviews", "personas", ["reviewer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "mod_reviews", type_="foreignkey")
    op.drop_column("mod_reviews", "reviewer_id")
    # ### end Alembic commands ###
