"""Added field mod_removed null false and default

Revision ID: 451fac274455
Revises: d832e3e0274c
Create Date: 2024-03-05 11:47:46.553444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "451fac274455"
down_revision: Union[str, None] = "d832e3e0274c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update posts set mod_removed = false where mod_removed is null")
    op.alter_column("posts", "mod_removed", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("posts", "mod_removed", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
