"""added completion_time

Revision ID: 4baa5f35aad5
Revises: e2ad28f80921
Create Date: 2023-11-28 12:22:10.233988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4baa5f35aad5"
down_revision: Union[str, None] = "e2ad28f80921"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rounds", sa.Column("completion_time", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rounds", "completion_time")
    # ### end Alembic commands ###
