"""Added token as index

Revision ID: 5583ed4737ca
Revises: 680157b667e4
Create Date: 2023-12-27 11:02:35.584479

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5583ed4737ca"
down_revision: Union[str, None] = "680157b667e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("token_index", "fcm_tokens", ["token"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("token_index", table_name="fcm_tokens")
    # ### end Alembic commands ###
