"""autoincrement on posts

Revision ID: 5a8544cafe46
Revises: 87ad2ba306b7
Create Date: 2023-10-20 09:54:12.326464

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "5a8544cafe46"
down_revision: Union[str, None] = "87ad2ba306b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
