"""Change persona image_id to nullable

Revision ID: 6172f2c83707
Revises: 13e1f5effca2
Create Date: 2023-10-18 09:59:58.894943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6172f2c83707"
down_revision: Union[str, None] = "13e1f5effca2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("personas", "image_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("personas", "image_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
