"""Added notification tokens table

Revision ID: 680157b667e4
Revises: acb7000e9b5a
Create Date: 2023-12-25 21:12:02.514015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ArrowType


# revision identifiers, used by Alembic.
revision: str = "680157b667e4"
down_revision: Union[str, None] = "acb7000e9b5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fcm_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("persona_id", sa.Integer(), nullable=False),
        sa.Column("creation_time", ArrowType(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index("pair_index", "fcm_tokens", ["token", "persona_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("pair_index", table_name="fcm_tokens")
    op.drop_table("fcm_tokens")
    # ### end Alembic commands ###
