"""Added added_community_bridges

Revision ID: 6becbe222f1c
Revises: 6d9319ef022b
Create Date: 2024-07-11 20:24:36.540423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6becbe222f1c'
down_revision: Union[str, None] = '6d9319ef022b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_bridges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('community_a_id', sa.Integer(), nullable=False),
    sa.Column('community_b_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('community_a_id <> community_b_id', name='community_a_not_equal_b'),
    sa.ForeignKeyConstraint(['community_a_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['community_b_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_a_id', 'community_b_id', name='bridge_distinct_communities')
    )
    op.create_index('bridge_index', 'community_bridges', ['community_a_id', 'community_b_id'], unique=True)
    op.add_column('communities', sa.Column('bridge_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'communities', 'community_bridges', ['bridge_id'], ['id'])
    op.alter_column(
        "communities",
        "access",
        existing_type=sa.Enum("public", "private", native_enum=False),
        type_=sa.Enum("public", "private", "bridged", native_enum=False),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bridge_distinct_communities', 'community_bridges', type_='unique')
    op.drop_constraint('community_a_not_equal_b', 'community_bridges', type_='check')
    op.drop_constraint('community_bridges_community_a_id_fkey', 'community_bridges', type_='foreignkey')
    op.drop_constraint('community_bridges_community_b_id_fkey', 'community_bridges', type_='foreignkey')
    
    op.drop_column('communities', 'bridge_id')
    op.drop_index('bridge_index', table_name='community_bridges')
    op.drop_table('community_bridges')
    op.alter_column(
        "communities",
        "access",
        existing_type=sa.Enum("public", "private", "bridged", native_enum=False),
        type_=sa.Enum("public", "private", native_enum=False),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
