"""Add pkh field to persona table

Revision ID: 6c196fca72f4
Revises: 1d3d63517e30
Create Date: 2023-10-10 12:24:45.397395

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c196fca72f4"
down_revision: Union[str, None] = "1d3d63517e30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("personas", sa.Column("pkh", sa.String(), nullable=True))

    # Personas are now identified by their pkh, so any old personas
    # in the database will be lost. We'll simply set their pkh to
    # the string version of their id to ensure uniquness.
    op.execute("""
update personas set pkh = cast(id as varchar) where pkh is null
""")
    op.alter_column("personas", "pkh", nullable=False)
    op.create_unique_constraint(None, "personas", ["pkh"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "personas", type_="unique")
    op.drop_column("personas", "pkh")
    # ### end Alembic commands ###
