"""Added available_mp3 flag

Revision ID: 6d9319ef022b
Revises: 451fac274455
Create Date: 2024-04-01 13:55:22.372089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d9319ef022b"
down_revision: Union[str, None] = "451fac274455"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audios",
        sa.Column(
            "available_mp3",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audios", "available_mp3")
    # ### end Alembic commands ###
