"""updates rounds and communities

Revision ID: 6f355f45ad34
Revises: 5a8544cafe46
Create Date: 2023-11-12 19:13:50.114909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f355f45ad34"
down_revision: Union[str, None] = "5a8544cafe46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("communities", sa.Column("round_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "communities", "rounds", ["round_id"], ["id"])
    op.add_column("prompts", sa.Column("status", sa.String(), nullable=False))
    op.drop_column("prompts", "responded_to")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompts",
        sa.Column("responded_to", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("prompts", "status")
    op.drop_constraint(None, "communities", type_="foreignkey")
    op.drop_column("communities", "round_id")
    # ### end Alembic commands ###
