"""Updated status mod_reviews

Revision ID: 91f7c98e4e4d
Revises: b61b13579768
Create Date: 2024-02-23 13:57:49.837321

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91f7c98e4e4d"
down_revision: Union[str, None] = "b61b13579768"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mod_reviews",
        "status",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.Enum("requested", "pending", "resolved", native_enum=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mod_reviews",
        "status",
        existing_type=sa.Enum("requested", "pending", "resolved", native_enum=False),
        type_=sa.VARCHAR(length=8),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
