"""Added unique index to permissions

Revision ID: 9329e37ffc0f
Revises: d4d809b80a9f
Create Date: 2024-01-11 14:33:04.145413

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9329e37ffc0f"
down_revision: Union[str, None] = "d4d809b80a9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("perm_index", "permissions", ["membership_id", "perm"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("perm_index", table_name="permissions")
    # ### end Alembic commands ###
