"""Added access field to communities

Revision ID: a114e2db5131
Revises: 399cfe3cc45b
Create Date: 2024-02-01 12:15:47.006055

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a114e2db5131"
down_revision: Union[str, None] = "399cfe3cc45b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "communities",
        sa.Column(
            "access", sa.Enum("public", "private", native_enum=False), nullable=True
        ),
    )
    # ### end Alembic commands ###
    # op.execute("update communities set access = 'public' where access is null")
    # op.alter_column('communities', 'access', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("communities", "access")
    # ### end Alembic commands ###
