"""Added Round notification flags

Revision ID: acb7000e9b5a
Revises: 7f70611c5fa9
Create Date: 2023-12-15 12:11:45.910836

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acb7000e9b5a"
down_revision: Union[str, None] = "7f70611c5fa9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rounds", sa.Column("start_notif_sent", sa.Boolean(), nullable=True))
    op.add_column(
        "rounds", sa.Column("completion_notif_sent", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rounds", "completion_notif_sent")
    op.drop_column("rounds", "start_notif_sent")
    # ### end Alembic commands ###
