"""Added timestamps to mod_reviews and mod_disputes models

Revision ID: b0d1252922e8
Revises: f0b01d80e281
Create Date: 2024-02-23 18:10:46.371347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ArrowType
import arrow

# revision identifiers, used by Alembic.
revision: str = "b0d1252922e8"
down_revision: Union[str, None] = "f0b01d80e281"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mod_disputes", sa.Column("creation_time", ArrowType(), nullable=True)
    )
    op.add_column(
        "mod_disputes", sa.Column("resolved_time", ArrowType(), nullable=True)
    )
    op.add_column("mod_reviews", sa.Column("creation_time", ArrowType(), nullable=True))

    op.execute(
        f"update mod_disputes set creation_time = '{arrow.utcnow()}' where creation_time is null"
    )
    op.execute(
        f"update mod_reviews set creation_time = '{arrow.utcnow()}' where creation_time is null"
    )

    op.alter_column("mod_disputes", "creation_time", nullable=False)
    op.alter_column("mod_reviews", "creation_time", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mod_reviews", "creation_time")
    op.drop_column("mod_disputes", "resolved_time")
    op.drop_column("mod_disputes", "creation_time")
    # ### end Alembic commands ###
