"""Added base mod models

Revision ID: b61b13579768
Revises: 3918b51efc35
Create Date: 2024-02-23 13:39:22.886892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b61b13579768"
down_revision: Union[str, None] = "3918b51efc35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mod_disputes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("disputer_id", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.Enum("pending", "resolved", native_enum=False), nullable=False
        ),
        sa.Column("info", sa.String(), nullable=True),
        sa.Column("metadata", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["disputer_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mod_reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dispute_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("pending", "resolved", native_enum=False), nullable=False
        ),
        sa.Column("info", sa.String(), nullable=True),
        sa.Column("metadata", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dispute_id"],
            ["mod_disputes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mod_reviews")
    op.drop_table("mod_disputes")
    # ### end Alembic commands ###
