"""Added unique pair community_roles

Revision ID: cae904fb793d
Revises: 0cc888c39995
Create Date: 2024-01-16 11:46:42.519741

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cae904fb793d"
down_revision: Union[str, None] = "0cc888c39995"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "role_unique_pair", "community_roles", ["membership_id", "role"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("role_unique_pair", table_name="community_roles")
    # ### end Alembic commands ###
