"""Added mode to perms and changed enum to string

Revision ID: d4d809b80a9f
Revises: 09f40a124cec
Create Date: 2024-01-11 14:25:10.165985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4d809b80a9f"
down_revision: Union[str, None] = "09f40a124cec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permissions",
        sa.Column(
            "mode", sa.Enum("grant", "revoke", native_enum=False), nullable=False
        ),
    )
    op.alter_column(
        "permissions", "perm", existing_type=sa.VARCHAR(length=11), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "permissions", "perm", existing_type=sa.VARCHAR(length=11), nullable=False
    )
    op.drop_column("permissions", "mode")
    # ### end Alembic commands ###
