"""Added members field to communities

Revision ID: d58569e80615
Revises: 6becbe222f1c
Create Date: 2024-08-04 22:32:02.143073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d58569e80615"
down_revision: Union[str, None] = "6becbe222f1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "communities",
        sa.Column("members_desc", sa.String(), server_default="", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("communities", "members_desc")
    # ### end Alembic commands ###
