"""Added field mod_removed

Revision ID: d832e3e0274c
Revises: 25ac367fac25
Create Date: 2024-03-05 10:53:45.237731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d832e3e0274c"
down_revision: Union[str, None] = "25ac367fac25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("mod_removed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "mod_removed")
    # ### end Alembic commands ###
