"""switches pointer for rounds and communities

Revision ID: e2ad28f80921
Revises: 6f355f45ad34
Create Date: 2023-11-13 22:14:17.552111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2ad28f80921"
down_revision: Union[str, None] = "6f355f45ad34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("communities_round_id_fkey", "communities", type_="foreignkey")
    op.drop_column("communities", "round_id")
    op.add_column("rounds", sa.Column("community_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "rounds", "communities", ["community_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rounds", type_="foreignkey")
    op.drop_column("rounds", "community_id")
    op.add_column(
        "communities",
        sa.Column("round_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "communities_round_id_fkey", "communities", "rounds", ["round_id"], ["id"]
    )
    # ### end Alembic commands ###
