"""Added ondelete CASCADE for membership_id in community_roles

Revision ID: e6d69dbd31f4
Revises: eac97dbb045b
Create Date: 2023-12-29 20:31:48.693655

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e6d69dbd31f4"
down_revision: Union[str, None] = "eac97dbb045b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "community_roles_membership_id_fkey", "community_roles", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "community_roles",
        "memberships",
        ["membership_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "community_roles", type_="foreignkey")
    op.create_foreign_key(
        "community_roles_membership_id_fkey",
        "community_roles",
        "memberships",
        ["membership_id"],
        ["id"],
    )
    # ### end Alembic commands ###
