"""Removed info from mod_reviews and mod_disputes models

Revision ID: f0b01d80e281
Revises: 91f7c98e4e4d
Create Date: 2024-02-23 18:09:15.421844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0b01d80e281"
down_revision: Union[str, None] = "91f7c98e4e4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mod_disputes", "info")
    op.drop_column("mod_reviews", "info")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mod_reviews",
        sa.Column("info", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "mod_disputes",
        sa.Column("info", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
