"""Add frequency_metadata table

Revision ID: f825b6e1b5b2
Revises: 151a1e05b9a5
Create Date: 2024-10-24 12:59:53.223173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ArrowType


# revision identifiers, used by Alembic.
revision: str = 'f825b6e1b5b2'
down_revision: Union[str, None] = '151a1e05b9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequency_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('msa_id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('creation_time', ArrowType(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msa_id'),
    sa.UniqueConstraint('persona_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequency_metadata')
    # ### end Alembic commands ###
