"""Add audio and image models

Revision ID: fddc819c8923
Revises: 6c196fca72f4
Create Date: 2023-10-17 11:58:18.796853

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fddc819c8923"
down_revision: Union[str, None] = "6c196fca72f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("info", sa.String(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("posts", sa.Column("audio_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "posts", "audios", ["audio_id"], ["id"])
    op.drop_column("posts", "audio_link")
    op.add_column("prompts", sa.Column("audio_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "prompts", "audios", ["audio_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prompts", type_="foreignkey")
    op.drop_column("prompts", "audio_id")
    op.add_column(
        "posts",
        sa.Column("audio_link", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "audio_id")
    op.drop_table("audios")
    # ### end Alembic commands ###
